### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by hazcod** [bdougie/loglify#18]
Hi,

How is one supposed to use this?
e.g. https://github.com/ironPeakServices/ironpeak.be/pull/28

However, no merges to master will trigger a deployment?

**Comment by hazcod** [comment]
ping @bdougie

**Comment by bdougie** [comment]
@hazcod thanks for opening this issue. I just confirmed that Action is not being triggered on PRs or pushes.

My hypothesis is the changes to Actions and how they run no longer playing well with Probot (what I used to bootstrap this Action) webhook events. 

I see the community has created a Probot adapter for GitHub Actions. 

https://github.com/probot/actions-adapter.

If you would like to use the GitHub App version of this project, it is available at https://github.com/apps/logs4netlify

**Comment by hazcod** [comment]
Thanks for the update @bdougie , but I've successfully switched over to niklasmerz/github-deployment-action
https://github.com/ironPeakServices/ironpeak.be/blob/master/.github/workflows/netlify.yaml#L20

**Comment by bdougie** [comment]
Perfect, niklasmerz/github-deployment-action looks like a good solution. I will still proceed with my fix but also update the docs to be more helpful in case other people stumble on to this.

**Comment by bdougie** [comment]
delisted from the marketplace. Making this an exclusive GitHub App and no longer an Action
